######################## default configuration ####################
baseURL = "https://www.open-source.church"
title = "Open Source Church"
theme = "hugo-osc"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "open-source-church" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["En"] # desable language from here
defaultContentLanguage = 'fr'
# Emoji, parce que voilà. https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji = true
googleAnalytics = "UA-153404165-1"
buildFuture = true # nécessaire pour inclure les événements

[taxonomies]
  tag = "tags"
  category = "categories"
[permalinks]
  blog = '/:year/:month/:slug/'
  event = '/event/:year/:month/:day/:slug/'
[frontmatter]
  date = ['date', ':filename', 'publishDate', 'lastmod']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
# link = "plugins/bootstrap/bootstrap.min.css"
link = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.compat.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.min.css"
# [[params.plugins.css]]
# link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
# link = "plugins/bootstrap/bootstrap.min.js"
link = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
# [[params.plugins.js]]
# link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "https://www.biblegateway.com/public/link-to-us/tooltips/bglinks.js"

#################### default parameters ################################
[params]
logo = "images/logo/logo.webp"
logo_small = "images/logo/logo-oneline.webp" # when navbar is small
# Meta data
description = "Open Source Church — une église en développement, par des geeks, pour des geeks."
author = "Open Source Church"
images = ["/images/banner/banner-osc.png"]
# contact info
address = "Lausanne"
mobile = ""
email = ""
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
# google_analitycs_id = "" # your id
# top header
top_header = false
# A second logo in the footer
[params.logo2]
path = "images/logo/logo_eerv.webp"
link = "https://www.eerv.ch"

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "" # replace this code with yours

# # google map
# [params.map]
# enable = true
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 2
  
############################# social site ########################

[[params.social]]
title = "discord"
icon = "discord" # teenyicons https://teenyicons.com/
link = "https://discord.gg/7FG3WvW"

[[params.social]]
title = "twitch"
icon = "twitch" # teenyicons
link = "https://www.twitch.tv/opensourcechurch"

[[params.social]]
title = "twitter"
icon = "twitter" # teenyicons
link = "https://twitter.com/Opnsourcechurch"

[[params.social]]
title = "instagram"
icon = "instagram" # teenyicons
link = "https://www.instagram.com/opensource.church"

[[params.social]]
title = "github"
icon = "github" # teenyicons
link = "https://github.com/open-source-church"

[[params.social]]
title = "youtube"
icon = "youtube" # teenyicons
link = "https://youtube.com/c/opensourcechurch"

[[params.social]]
title = "mastodon"
icon = "mastodon" # teenyicons
link = "https://tooting.ch/@osc"
rel = "me"

[[params.social]]
title = "facebook"
icon = "facebook" # teenyicons
link = "https://facebook.com/opensourcechurch"

# [[params.social]]
# title = "newsletter"
# icon = "at" # teenyicons
# link = ""

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"

################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

# footer menu

[[Languages.en.menu.footer]]
name = "event"
url = "event"

################################### French language #####################################
[Languages.fr]
languageName = "Français"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 1
home = "Accueil"
# copyright
copyright = "Powered by [Hugo](https://gohugo.io/) · thème [hugo-osc](https://github.com/open-source-church/open-source.church/tree/main/themes/hugo-osc) basé sur [educenter](https://github.com/themefisher/educenter-hugo) par [Themefisher](https://themefisher.com/hugo-themes/)"

################### French navigation ####################

# main menu


[[Languages.fr.menu.main]]
name = "Blog"
url = "blog"
weight = 1

[[Languages.fr.menu.main]]
name = "Évènements"
url = "event"
weight = 2

[[Languages.fr.menu.main]]
name = "Activités"
url = "activities"
weight = 3

[[Languages.fr.menu.main]]
name = "À propos"
weight = 4

  [[Languages.fr.menu.main]]
  parent = "À propos"
  name = "Open Source Church"
  url = "about"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "À propos"
  name = "Contribuer"
  url = "contribuer"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "À propos"
  name = "Media"
  url = "media"
  weight = 4
  
# [[Languages.fr.menu.main]]
# name = "Contact"
# url = "contact"
# weight = 5

# footer menu

[[Languages.fr.menu.footer]]
name = "Réseau protestant"
url = "pages/reseau-protestant"

[[Languages.fr.menu.footer]]
name = "Holygames"
url = "https://www.holygames.ch"

[[Languages.fr.menu.footer]]
name = "In Fabula Veritas"
url = "https://infabulaveritas.ch"
